<?php

namespace App\Services\Export;

use App\Models\Barangay;
use App\Models\Municipality;
use App\Models\MunicipalityYearlySummary;
use App\Models\SocialWelfareProgram;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Chart\Chart;
use PhpOffice\PhpSpreadsheet\Chart\DataSeries;
use PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues;
use PhpOffice\PhpSpreadsheet\Chart\Legend;
use PhpOffice\PhpSpreadsheet\Chart\PlotArea;
use PhpOffice\PhpSpreadsheet\Chart\Title;
use PhpOffice\PhpSpreadsheet\Chart\Layout;

/**
 * DataExcelExportService
 *
 * 7-sheet workbook:
 *  Sheet 1 – Municipality Yearly Data  (table)
 *  Sheet 2 – Municipality Charts        (3 charts)
 *  Sheet 3 – Barangay Data             (table)
 *  Sheet 4 – Barangay Charts           (2 charts)
 *  Sheet 5 – Social Programs           (table)
 *  Sheet 6 – Programs Charts           (column + pie)
 *  Sheet 7 – Export Summary
 */
class DataExcelExportService
{
    // ── MSWDO Brand Colors ────────────────────────────────────────
    const COLOR_PRIMARY   = '2C3E8F';
    const COLOR_SECONDARY = 'FDB913';
    const COLOR_RED       = 'C41E24';
    const COLOR_WHITE     = 'FFFFFF';
    const COLOR_BORDER    = 'CBD5E1';
    const COLOR_ALT_ROW   = 'EEF2FF';
    const COLOR_DARK_TEXT = '1E293B';
    const COLOR_MID_TEXT  = '475569';

    const FONT_TITLE  = 14;
    const FONT_HEADER = 10;
    const FONT_BODY   = 9;

    // Distinct colors for multi-series / pie slices
    const PALETTE = [
        '2C3E8F', 'FDB913', 'C41E24', '16A34A', '7C3AED',
        'EA580C', '0891B2', 'BE185D', '65A30D', '9333EA',
    ];

    // ══════════════════════════════════════════════════════════════
    //  PUBLIC: generate workbook
    // ══════════════════════════════════════════════════════════════

    public function generateWorkbook(array $filters = []): string
    {
        $municipality = $filters['municipality'] ?? null;
        $year = isset($filters['year']) && $filters['year'] !== 'all' && $filters['year'] !== ''
            ? (int) $filters['year'] : null;

        $muniRecords = $this->fetchMunicipalityData($municipality, $year);
        $brgyRecords = $this->fetchBarangayData($municipality, $year);
        $progRecords = $this->fetchProgramData($municipality, $year);

        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setCreator('MSWDO Analysis System')
            ->setTitle('MSWDO Data Export')
            ->setSubject('Municipal Social Welfare Data')
            ->setDescription('Generated by MSWDO Analysis System.');

        // Sheet 1 – Municipality data table
        $shMuni = $spreadsheet->getActiveSheet()->setTitle('Municipality Yearly Data');
        $this->buildMunicipalitySheet($shMuni, $muniRecords, $municipality, $year);

        // Sheet 2 – Municipality charts
        $shMuniC = $spreadsheet->createSheet()->setTitle('Municipality Charts');
        $this->buildMunicipalityCharts($shMuniC, $muniRecords);

        // Sheet 3 – Barangay data table
        $shBrgy = $spreadsheet->createSheet()->setTitle('Barangay Data');
        $this->buildBarangaySheet($shBrgy, $brgyRecords, $municipality, $year);

        // Sheet 4 – Barangay charts
        $shBrgyC = $spreadsheet->createSheet()->setTitle('Barangay Charts');
        $this->buildBarangayCharts($shBrgyC, $brgyRecords);

        // Sheet 5 – Social Programs data table
        $shProg = $spreadsheet->createSheet()->setTitle('Social Programs');
        $this->buildProgramsSheet($shProg, $progRecords, $municipality, $year);

        // Sheet 6 – Programs charts
        $shProgC = $spreadsheet->createSheet()->setTitle('Programs Charts');
        $this->buildProgramsCharts($shProgC, $progRecords);

        // Sheet 7 – Summary
        $shSumm = $spreadsheet->createSheet()->setTitle('Export Summary');
        $this->buildSummarySheet($shSumm, $muniRecords, $brgyRecords, $progRecords, $municipality, $year, $filters);

        $spreadsheet->setActiveSheetIndex(0);

        $tempDir = storage_path('app/temp/data_exports');
        if (!is_dir($tempDir)) {
            mkdir($tempDir, 0755, true);
        }
        $filePath = $tempDir . DIRECTORY_SEPARATOR . uniqid('data_export_', true) . '.xlsx';
        $writer   = new Xlsx($spreadsheet);
        $writer->setIncludeCharts(true);
        $writer->save($filePath);

        return $filePath;
    }

    // ══════════════════════════════════════════════════════════════
    //  DATA FETCHERS
    // ══════════════════════════════════════════════════════════════

    private function fetchMunicipalityData(?string $m, ?int $y): \Illuminate\Support\Collection
    {
        $q = MunicipalityYearlySummary::query()->orderBy('municipality')->orderBy('year', 'desc');
        if ($m) $q->where('municipality', $m);
        if ($y) $q->where('year', $y);
        return $q->get();
    }

    private function fetchBarangayData(?string $m, ?int $y): \Illuminate\Support\Collection
    {
        $q = Barangay::query()->orderBy('municipality')->orderBy('name')->orderBy('year', 'desc');
        if ($m) $q->where('municipality', $m);
        if ($y) $q->where('year', $y);
        return $q->get();
    }

    private function fetchProgramData(?string $m, ?int $y): \Illuminate\Support\Collection
    {
        $q = SocialWelfareProgram::query()->orderBy('municipality')->orderBy('year', 'desc')->orderBy('program_type');
        if ($m) $q->where('municipality', $m);
        if ($y) $q->where('year', $y);
        return $q->get();
    }

    // ══════════════════════════════════════════════════════════════
    //  DATA TABLE SHEETS
    // ══════════════════════════════════════════════════════════════

    private function buildMunicipalitySheet(Worksheet $sheet, $records, ?string $m, ?int $y): void
    {
        $headers = ['Year','Municipality','Total Population','Male','Female','Age 0–19','Age 20–59','Age 60+','Households'];
        $this->writeSheetTitle($sheet, 'Municipality Yearly Data', $this->buildSubtitle($m, $y), count($headers));
        $hRow = 4;
        $this->writeHeaders($sheet, $hRow, $headers, self::COLOR_PRIMARY);
        $row = $hRow + 1;
        foreach ($records as $i => $r) {
            $this->writeDataRow($sheet, $row, [
                $r->year, $r->municipality,
                (int)($r->total_population ?? 0), (int)($r->male_population ?? 0),
                (int)($r->female_population ?? 0), (int)($r->population_0_19 ?? 0),
                (int)($r->population_20_59 ?? 0), (int)($r->population_60_100 ?? 0),
                (int)($r->total_households ?? 0),
            ], $i % 2 === 0);
            foreach (['C','D','E','F','G','H','I'] as $c) {
                $sheet->getCell($c.$row)->getStyle()->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
            }
            $row++;
        }
        if ($records->isEmpty()) {
            $this->writeEmptyState($sheet, $hRow + 1, count($headers), 'No municipality yearly data available.');
        }
        $this->applySheetLayout($sheet, count($headers), $row - 1, $hRow,
            ['A'=>8,'B'=>22,'C'=>18,'D'=>12,'E'=>12,'F'=>12,'G'=>12,'H'=>12,'I'=>14], 'landscape');
    }

    private function buildBarangaySheet(Worksheet $sheet, $records, ?string $m, ?int $y): void
    {
        $headers = ['Year','Municipality','Barangay','Total Population','PWD','AICS','Solo Parent','Households','4Ps','Senior'];
        $this->writeSheetTitle($sheet, 'Barangay Data', $this->buildSubtitle($m, $y), count($headers));
        $hRow = 4;
        $this->writeHeaders($sheet, $hRow, $headers, self::COLOR_PRIMARY);
        $row = $hRow + 1;
        foreach ($records as $i => $b) {
            $this->writeDataRow($sheet, $row, [
                $b->year ?? '', $b->municipality, $b->name,
                (int)($b->total_population ?? 0), (int)($b->pwd_count ?? 0),
                (int)($b->aics_count ?? 0), (int)($b->single_parent_count ?? 0),
                (int)($b->total_households ?? 0), (int)($b->four_ps_count ?? 0),
                (int)($b->senior_count ?? 0),
            ], $i % 2 === 0);
            foreach (['D','E','F','G','H','I','J'] as $c) {
                $sheet->getCell($c.$row)->getStyle()->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
            }
            $row++;
        }
        if ($records->isEmpty()) {
            $this->writeEmptyState($sheet, $hRow + 1, count($headers), 'No barangay data available.');
        }
        $this->applySheetLayout($sheet, count($headers), $row - 1, $hRow,
            ['A'=>8,'B'=>22,'C'=>24,'D'=>16,'E'=>10,'F'=>10,'G'=>14,'H'=>14,'I'=>10,'J'=>10], 'landscape');
    }

    private function buildProgramsSheet(Worksheet $sheet, $records, ?string $m, ?int $y): void
    {
        // Use PRIMARY blue for header — NOT red
        $headers = ['Year','Municipality','Program Type','Beneficiary Count'];
        $this->writeSheetTitle($sheet, 'Social Programs', $this->buildSubtitle($m, $y), count($headers));
        $hRow = 4;
        $this->writeHeaders($sheet, $hRow, $headers, self::COLOR_PRIMARY);
        $row = $hRow + 1;
        foreach ($records as $i => $p) {
            $this->writeDataRow($sheet, $row, [
                $p->year, $p->municipality,
                str_replace('_', ' ', $p->program_type),
                (int)($p->beneficiary_count ?? 0),
            ], $i % 2 === 0);
            $sheet->getCell('D'.$row)->getStyle()->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
            $row++;
        }
        if ($records->isEmpty()) {
            $this->writeEmptyState($sheet, $hRow + 1, count($headers), 'No social program data available.');
        }
        $this->applySheetLayout($sheet, count($headers), $row - 1, $hRow,
            ['A'=>8,'B'=>24,'C'=>28,'D'=>18], 'portrait');
    }

    // ══════════════════════════════════════════════════════════════
    //  CHART SHEETS
    // Charts use in-memory arrays (no cell-reference issues).
    // Data is also written to a visible helper table on the sheet
    // so users can see the exact numbers behind each chart.
    // ══════════════════════════════════════════════════════════════

    /** Sheet 2 — Municipality Charts */
    private function buildMunicipalityCharts(Worksheet $sheet, $records): void
    {
        $this->writeChartSheetTitle($sheet, 'Municipality Yearly Data — Charts');

        if ($records->isEmpty()) {
            $sheet->setCellValue('A4', 'No data available to chart. Please add municipality yearly data first.');
            $sheet->getStyle('A4')->getFont()->setItalic(true)->setSize(10)->setColor((new Color())->setRGB(self::COLOR_MID_TEXT));
            return;
        }

        // Aggregate: latest year per municipality
        $byMuni  = $records->groupBy('municipality')->map(fn($rows) => $rows->sortByDesc('year')->first());
        $labels  = $byMuni->keys()->values()->toArray();
        $pop     = $byMuni->map(fn($r) => (int)($r->total_population   ?? 0))->values()->toArray();
        $male    = $byMuni->map(fn($r) => (int)($r->male_population    ?? 0))->values()->toArray();
        $female  = $byMuni->map(fn($r) => (int)($r->female_population  ?? 0))->values()->toArray();
        $hh      = $byMuni->map(fn($r) => (int)($r->total_households   ?? 0))->values()->toArray();
        $n       = count($labels);

        // ── Write visible data table ──────────────────────────────
        $tRow = 4;
        $this->writeChartDataTable($sheet, $tRow, 'A',
            ['Municipality', 'Total Population', 'Male', 'Female', 'Households'],
            array_map(null, $labels, $pop, $male, $female, $hh)
        );

        // Chart start row (below table + gap)
        $chartTop = $tRow + $n + 3;

        // ── Chart 1: Total Population ─────────────────────────────
        $c1 = $this->makeColumnChartFromArrays(
            'ch_muni_pop', 'Total Population by Municipality',
            $labels,
            [['label' => 'Total Population', 'data' => $pop, 'color' => self::PALETTE[0]]]
        );
        $c1->setTopLeftPosition($this->rowToCell('A', $chartTop));
        $c1->setBottomRightPosition($this->rowToCell('I', $chartTop + 20));
        $sheet->addChart($c1);

        // ── Chart 2: Male vs Female ───────────────────────────────
        $c2 = $this->makeColumnChartFromArrays(
            'ch_muni_gender', 'Male vs Female Population',
            $labels,
            [
                ['label' => 'Male',   'data' => $male,   'color' => self::PALETTE[0]],
                ['label' => 'Female', 'data' => $female, 'color' => self::PALETTE[2]],
            ]
        );
        $c2->setTopLeftPosition($this->rowToCell('A', $chartTop + 22));
        $c2->setBottomRightPosition($this->rowToCell('I', $chartTop + 42));
        $sheet->addChart($c2);

        // ── Chart 3: Households ───────────────────────────────────
        $c3 = $this->makeColumnChartFromArrays(
            'ch_muni_hh', 'Households by Municipality',
            $labels,
            [['label' => 'Households', 'data' => $hh, 'color' => self::PALETTE[3]]]
        );
        $c3->setTopLeftPosition($this->rowToCell('A', $chartTop + 44));
        $c3->setBottomRightPosition($this->rowToCell('I', $chartTop + 64));
        $sheet->addChart($c3);

        $this->applyChartSheetLayout($sheet);
    }

    /** Sheet 4 — Barangay Charts */
    private function buildBarangayCharts(Worksheet $sheet, $records): void
    {
        $this->writeChartSheetTitle($sheet, 'Barangay Data — Charts');

        if ($records->isEmpty()) {
            $sheet->setCellValue('A4', 'No data available to chart. Please add barangay data first.');
            $sheet->getStyle('A4')->getFont()->setItalic(true)->setSize(10)->setColor((new Color())->setRGB(self::COLOR_MID_TEXT));
            return;
        }

        // Use latest year per barangay, top 15 by population
        $byBrgy  = $records->groupBy(fn($r) => $r->municipality.'|'.$r->name)
            ->map(fn($rows) => $rows->sortByDesc('year')->first())
            ->sortByDesc('total_population')
            ->take(15)->values();

        $labels = $byBrgy->map(fn($r) => substr($r->name, 0, 16))->toArray();
        $pop    = $byBrgy->map(fn($r) => (int)($r->total_population   ?? 0))->toArray();
        $pwd    = $byBrgy->map(fn($r) => (int)($r->pwd_count          ?? 0))->toArray();
        $aics   = $byBrgy->map(fn($r) => (int)($r->aics_count         ?? 0))->toArray();
        $sp     = $byBrgy->map(fn($r) => (int)($r->single_parent_count?? 0))->toArray();
        $ps     = $byBrgy->map(fn($r) => (int)($r->four_ps_count      ?? 0))->toArray();
        $senior = $byBrgy->map(fn($r) => (int)($r->senior_count       ?? 0))->toArray();
        $n      = count($labels);

        // Write visible data table
        $tRow = 4;
        $this->writeChartDataTable($sheet, $tRow, 'A',
            ['Barangay','Population','PWD','AICS','Solo Parent','4Ps','Senior'],
            array_map(null, $labels, $pop, $pwd, $aics, $sp, $ps, $senior)
        );

        $chartTop = $tRow + $n + 3;

        // Chart 1: Bar — Population per Barangay
        $c1 = $this->makeBarChartFromArrays(
            'ch_brgy_pop', 'Total Population by Barangay (Top '.$n.')',
            $labels,
            [['label' => 'Population', 'data' => $pop, 'color' => self::PALETTE[0]]]
        );
        $c1->setTopLeftPosition($this->rowToCell('A', $chartTop));
        $c1->setBottomRightPosition($this->rowToCell('I', $chartTop + 22));
        $sheet->addChart($c1);

        // Chart 2: Column — Welfare indicators
        $c2 = $this->makeColumnChartFromArrays(
            'ch_brgy_welfare', 'Welfare Indicators by Barangay',
            $labels,
            [
                ['label' => 'PWD',         'data' => $pwd,    'color' => self::PALETTE[0]],
                ['label' => 'AICS',        'data' => $aics,   'color' => self::PALETTE[1]],
                ['label' => 'Solo Parent', 'data' => $sp,     'color' => self::PALETTE[2]],
                ['label' => '4Ps',         'data' => $ps,     'color' => self::PALETTE[3]],
                ['label' => 'Senior',      'data' => $senior, 'color' => self::PALETTE[4]],
            ]
        );
        $c2->setTopLeftPosition($this->rowToCell('A', $chartTop + 24));
        $c2->setBottomRightPosition($this->rowToCell('I', $chartTop + 46));
        $sheet->addChart($c2);

        $this->applyChartSheetLayout($sheet);
    }

    /** Sheet 6 — Programs Charts */
    private function buildProgramsCharts(Worksheet $sheet, $records): void
    {
        $this->writeChartSheetTitle($sheet, 'Social Programs — Charts');

        if ($records->isEmpty()) {
            $sheet->setCellValue('A4', 'No data available to chart. Please add social program data first.');
            $sheet->getStyle('A4')->getFont()->setItalic(true)->setSize(10)->setColor((new Color())->setRGB(self::COLOR_MID_TEXT));
            return;
        }

        // Aggregate total beneficiaries per program type
        $byProg  = $records->groupBy('program_type')
            ->map(fn($rows) => $rows->sum('beneficiary_count'))
            ->sortDesc();

        $labels  = $byProg->keys()->map(fn($p) => str_replace('_', ' ', $p))->values()->toArray();
        $counts  = $byProg->values()->toArray();
        $n       = count($labels);

        // Write visible data table
        $tRow = 4;
        $this->writeChartDataTable($sheet, $tRow, 'A',
            ['Program Type', 'Total Beneficiaries'],
            array_map(null, $labels, $counts)
        );

        $chartTop = $tRow + $n + 3;

        // Chart 1: Multi-color column — Beneficiaries by Program
        $colors = array_slice(self::PALETTE, 0, $n);
        $svCol  = new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, $n, $counts);
        $svCol->setFillColor($colors);
        $catCol = [new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, $n, $labels)];
        $lblCol = [new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 1, ['Beneficiaries'])];
        $dsCol  = new DataSeries(DataSeries::TYPE_BARCHART, DataSeries::GROUPING_CLUSTERED, [0], $lblCol, $catCol, [$svCol]);
        $dsCol->setPlotDirection(DataSeries::DIRECTION_COL);
        $c1 = new Chart('ch_prog_col', new Title('Beneficiaries by Program Type'),
            new Legend(Legend::POSITION_BOTTOM, new Layout(), false),
            new PlotArea(new Layout(), [$dsCol]), true, 0, null, null);
        $c1->setTopLeftPosition($this->rowToCell('A', $chartTop));
        $c1->setBottomRightPosition($this->rowToCell('I', $chartTop + 22));
        $sheet->addChart($c1);

        // Chart 2: Pie chart
        $svPie  = new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, $n, $counts);
        $svPie->setFillColor($colors);
        $catPie = [new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, $n, $labels)];
        $lblPie = [new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 1, ['Programs'])];
        $dsPie  = new DataSeries(DataSeries::TYPE_PIECHART, null, [0], $lblPie, $catPie, [$svPie]);
        $pieLayout = new Layout();
        $pieLayout->setShowPercent(true);
        $pieLayout->setShowCatName(true);
        $pieLayout->setShowVal(false);
        $c2 = new Chart('ch_prog_pie', new Title('Beneficiary Distribution (%)'),
            new Legend(Legend::POSITION_RIGHT, new Layout(), false),
            new PlotArea($pieLayout, [$dsPie]), true, 0, null, null);
        $c2->setTopLeftPosition($this->rowToCell('A', $chartTop + 24));
        $c2->setBottomRightPosition($this->rowToCell('I', $chartTop + 46));
        $sheet->addChart($c2);

        $this->applyChartSheetLayout($sheet);
    }

    // ══════════════════════════════════════════════════════════════
    //  CHART FACTORY HELPERS  (array-based, no cell references)
    // ══════════════════════════════════════════════════════════════

    /**
     * Build a clustered column chart from PHP arrays.
     * $series = [['label'=>'...', 'data'=>[...], 'color'=>'hex'], ...]
     */
    private function makeColumnChartFromArrays(string $id, string $title, array $categories, array $series): Chart
    {
        $n     = count($categories);
        $cats  = [new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, $n, $categories)];
        $lbls  = [];
        $vals  = [];
        foreach ($series as $s) {
            $lbls[] = new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 1, [$s['label']]);
            $sv = new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, count($s['data']), $s['data']);
            $sv->setFillColor($s['color']);
            $vals[] = $sv;
        }
        $ds = new DataSeries(DataSeries::TYPE_BARCHART, DataSeries::GROUPING_CLUSTERED,
            range(0, count($series) - 1), $lbls, $cats, $vals);
        $ds->setPlotDirection(DataSeries::DIRECTION_COL);
        return new Chart($id, new Title($title),
            new Legend(Legend::POSITION_BOTTOM, new Layout(), false),
            new PlotArea(new Layout(), [$ds]), true, 0, null, null);
    }

    /**
     * Build a horizontal bar chart from PHP arrays.
     */
    private function makeBarChartFromArrays(string $id, string $title, array $categories, array $series): Chart
    {
        $n    = count($categories);
        $cats = [new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, $n, $categories)];
        $lbls = [];
        $vals = [];
        foreach ($series as $s) {
            $lbls[] = new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 1, [$s['label']]);
            $sv = new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, count($s['data']), $s['data']);
            $sv->setFillColor($s['color']);
            $vals[] = $sv;
        }
        $ds = new DataSeries(DataSeries::TYPE_BARCHART, DataSeries::GROUPING_CLUSTERED,
            range(0, count($series) - 1), $lbls, $cats, $vals);
        $ds->setPlotDirection(DataSeries::DIRECTION_BAR);
        return new Chart($id, new Title($title),
            new Legend(Legend::POSITION_BOTTOM, new Layout(), false),
            new PlotArea(new Layout(), [$ds]), true, 0, null, null);
    }

    // ══════════════════════════════════════════════════════════════
    //  HELPER: visible data table on chart sheets
    // ══════════════════════════════════════════════════════════════

    /**
     * Write a small, styled data table onto the chart sheet so users
     * can see the numbers behind each chart.
     *
     * @param array $headers  Column headers
     * @param array $rows     Array of row arrays (values aligned to $headers)
     */
    private function writeChartDataTable(Worksheet $sheet, int $startRow, string $startCol, array $headers, array $rows): void
    {
        $colCount = count($headers);
        $startColIdx = Coordinate::columnIndexFromString($startCol);

        // Header row
        foreach ($headers as $i => $h) {
            $col = Coordinate::stringFromColumnIndex($startColIdx + $i);
            $sheet->setCellValue($col.$startRow, $h);
        }
        $endCol = Coordinate::stringFromColumnIndex($startColIdx + $colCount - 1);
        $range  = "{$startCol}{$startRow}:{$endCol}{$startRow}";
        $sheet->getStyle($range)->applyFromArray([
            'font'      => ['bold' => true, 'size' => 9, 'color' => ['rgb' => self::COLOR_WHITE]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => self::COLOR_PRIMARY]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => self::COLOR_BORDER]]],
        ]);
        $sheet->getRowDimension($startRow)->setRowHeight(20);

        // Set column widths
        for ($i = 0; $i < $colCount; $i++) {
            $col = Coordinate::stringFromColumnIndex($startColIdx + $i);
            $sheet->getColumnDimension($col)->setWidth($i === 0 ? 22 : 16);
        }

        // Data rows
        foreach ($rows as $rIdx => $rowData) {
            $r = $startRow + 1 + $rIdx;
            $alt = ($rIdx % 2 === 0);
            foreach ((array)$rowData as $i => $val) {
                $col = Coordinate::stringFromColumnIndex($startColIdx + $i);
                $sheet->setCellValue($col.$r, $val ?? 0);
            }
            $rowRange = "{$startCol}{$r}:{$endCol}{$r}";
            $sheet->getStyle($rowRange)->applyFromArray([
                'font'      => ['size' => 9],
                'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $alt ? self::COLOR_ALT_ROW : self::COLOR_WHITE]],
                'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
                'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => self::COLOR_BORDER]]],
            ]);
            // Right-align numeric columns
            for ($i = 1; $i < $colCount; $i++) {
                $col = Coordinate::stringFromColumnIndex($startColIdx + $i);
                $sheet->getStyle($col.$r)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
                $sheet->getStyle($col.$r)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
            }
            $sheet->getRowDimension($r)->setRowHeight(15);
        }
    }

    // ══════════════════════════════════════════════════════════════
    //  SUMMARY SHEET
    // ══════════════════════════════════════════════════════════════

    private function buildSummarySheet(Worksheet $sheet, $muniRecords, $brgyRecords, $progRecords, ?string $m, ?int $y, array $filters): void
    {
        $sheet->mergeCells('A1:C1');
        $sheet->setCellValue('A1', 'MSWDO DATA EXPORT SUMMARY');
        $this->applyTitleStyle($sheet, 'A1:C1', self::COLOR_PRIMARY, true);
        $sheet->getRowDimension(1)->setRowHeight(36);

        $sheet->mergeCells('A2:C2');
        $sheet->setCellValue('A2', 'Municipal Social Welfare and Development Office');
        $sheet->getStyle('A2:C2')->getFont()->setSize(10)->setItalic(true)->setColor((new Color())->setRGB(self::COLOR_MID_TEXT));
        $sheet->getStyle('A2:C2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $sheet->getRowDimension(2)->setRowHeight(18);
        $sheet->mergeCells('A3:C3');
        $sheet->getRowDimension(3)->setRowHeight(8);

        $infoRow = 4;
        foreach ([
            ['Report Title',       'MSWDO Comparative Socio-Economic Data Export'],
            ['Export Date & Time', now()->format('F j, Y \a\t g:i A')],
            ['Municipality',       $m ?: 'All Municipalities'],
            ['Year',               $y ? (string)$y : 'All Years'],
            ['Category Filter',    ucfirst($filters['category'] ?? 'all')],
        ] as $item) {
            $sheet->setCellValue('A'.$infoRow, $item[0]);
            $sheet->setCellValue('B'.$infoRow, $item[1]);
            $sheet->mergeCells('B'.$infoRow.':C'.$infoRow);
            $sheet->getStyle('A'.$infoRow)->getFont()->setBold(true)->setSize(self::FONT_BODY)->setColor((new Color())->setRGB(self::COLOR_PRIMARY));
            $sheet->getStyle('B'.$infoRow)->getFont()->setSize(self::FONT_BODY)->setColor((new Color())->setRGB(self::COLOR_DARK_TEXT));
            $sheet->getRowDimension($infoRow)->setRowHeight(16);
            $infoRow++;
        }
        $infoRow++;

        // Workbook contents index
        $this->writeSummarySection($sheet, $infoRow, 'WORKBOOK CONTENTS');
        $infoRow++;
        foreach ([
            ['Sheet 1', 'Municipality Yearly Data',  'Population, households, age groups per municipality/year'],
            ['Sheet 2', 'Municipality Charts',        '3 charts: Total Population, Male vs Female, Households'],
            ['Sheet 3', 'Barangay Data',              'PWD, AICS, Solo Parent, 4Ps, Senior per barangay'],
            ['Sheet 4', 'Barangay Charts',            '2 charts: Population bar, Welfare indicators column'],
            ['Sheet 5', 'Social Programs',            'Beneficiary counts per program type'],
            ['Sheet 6', 'Programs Charts',            'Column chart + Pie chart of beneficiary distribution'],
            ['Sheet 7', 'Export Summary',             'This sheet — metadata and record statistics'],
        ] as $idx => $si) {
            $sheet->setCellValue('A'.$infoRow, $si[0]);
            $sheet->setCellValue('B'.$infoRow, $si[1]);
            $sheet->setCellValue('C'.$infoRow, $si[2]);
            $sheet->getStyle('A'.$infoRow)->getFont()->setBold(true)->setSize(self::FONT_BODY)->setColor((new Color())->setRGB(self::COLOR_PRIMARY));
            $sheet->getStyle('B'.$infoRow)->getFont()->setSize(self::FONT_BODY);
            $sheet->getStyle('C'.$infoRow)->getFont()->setSize(8)->setColor((new Color())->setRGB(self::COLOR_MID_TEXT));
            if ($idx % 2 === 1) {
                $sheet->getStyle("A{$infoRow}:C{$infoRow}")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::COLOR_ALT_ROW);
            }
            $sheet->getRowDimension($infoRow)->setRowHeight(15);
            $infoRow++;
        }
        $infoRow++;

        // Record stats
        $this->writeSummarySection($sheet, $infoRow, 'EXPORT STATISTICS');
        $infoRow++;
        foreach ([
            ['Municipality Yearly Records', $muniRecords->count()],
            ['Barangay Records',            $brgyRecords->count()],
            ['Social Program Records',      $progRecords->count()],
            ['Total Records',               $muniRecords->count() + $brgyRecords->count() + $progRecords->count()],
        ] as $i => $s) {
            $sheet->setCellValue('A'.$infoRow, $s[0]);
            $sheet->setCellValue('B'.$infoRow, $s[1]);
            $sheet->mergeCells('B'.$infoRow.':C'.$infoRow);
            $sheet->getStyle('B'.$infoRow)->getFont()->setBold(true)->setSize(self::FONT_BODY);
            $sheet->getStyle('B'.$infoRow)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
            if ($i % 2 === 1) {
                $sheet->getStyle("A{$infoRow}:C{$infoRow}")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::COLOR_ALT_ROW);
            }
            $sheet->getRowDimension($infoRow)->setRowHeight(16);
            $infoRow++;
        }

        if ($muniRecords->isNotEmpty()) {
            $infoRow++;
            $this->writeSummarySection($sheet, $infoRow, 'DEMOGRAPHIC TOTALS');
            $infoRow++;
            foreach ([
                ['Total Population (sum)',  $muniRecords->sum('total_population')],
                ['Total Households (sum)',   $muniRecords->sum('total_households')],
                ['Total Male (sum)',         $muniRecords->sum('male_population')],
                ['Total Female (sum)',       $muniRecords->sum('female_population')],
            ] as $i => $t) {
                $sheet->setCellValue('A'.$infoRow, $t[0]);
                $sheet->setCellValue('B'.$infoRow, $t[1]);
                $sheet->mergeCells('B'.$infoRow.':C'.$infoRow);
                $sheet->getStyle('B'.$infoRow)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
                if ($i % 2 === 1) {
                    $sheet->getStyle("A{$infoRow}:C{$infoRow}")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::COLOR_ALT_ROW);
                }
                $sheet->getRowDimension($infoRow)->setRowHeight(16);
                $infoRow++;
            }
        }

        if ($progRecords->isNotEmpty()) {
            $infoRow++;
            $sheet->setCellValue('A'.$infoRow, 'Total Social Program Beneficiaries:');
            $sheet->setCellValue('B'.$infoRow, $progRecords->sum('beneficiary_count'));
            $sheet->mergeCells('B'.$infoRow.':C'.$infoRow);
            $sheet->getStyle('A'.$infoRow)->getFont()->setBold(true)->setSize(self::FONT_BODY);
            $sheet->getStyle('B'.$infoRow)->getFont()->setBold(true)->setSize(self::FONT_BODY);
            $sheet->getStyle('B'.$infoRow)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
            $sheet->getRowDimension($infoRow)->setRowHeight(16);
            $infoRow++;
        }

        $infoRow++;
        $sheet->mergeCells("A{$infoRow}:C{$infoRow}");
        $sheet->setCellValue("A{$infoRow}", 'DISCLAIMER');
        $sheet->getStyle("A{$infoRow}:C{$infoRow}")->getFont()->setBold(true)->setSize(9)->setColor((new Color())->setRGB(self::COLOR_RED));
        $infoRow++;
        $sheet->mergeCells("A{$infoRow}:C{$infoRow}");
        $sheet->setCellValue("A{$infoRow}", 'This report was generated by the MSWDO Analysis System. Data is based on official records and should be used for reference purposes only.');
        $sheet->getStyle("A{$infoRow}:C{$infoRow}")->getFont()->setSize(8)->setItalic(true);
        $sheet->getStyle("A{$infoRow}:C{$infoRow}")->getAlignment()->setWrapText(true)->setVertical(Alignment::VERTICAL_TOP);
        $sheet->getRowDimension($infoRow)->setRowHeight(40);

        $sheet->getColumnDimension('A')->setWidth(42);
        $sheet->getColumnDimension('B')->setWidth(32);
        $sheet->getColumnDimension('C')->setWidth(28);

        $sheet->getPageSetup()
            ->setOrientation(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_PORTRAIT)
            ->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4)
            ->setFitToWidth(1)->setFitToHeight(0)->setHorizontalCentered(true);
        $sheet->getPageMargins()->setTop(0.75)->setBottom(0.75)->setLeft(0.75)->setRight(0.75);
        $sheet->getHeaderFooter()
            ->setOddHeader('&C&"Arial,Bold"&12MSWDO Data Export Summary')
            ->setOddFooter('&L'.now()->format('Y-m-d').'&CPage &P of &N&RConfidential');
    }

    private function writeSummarySection(Worksheet $sheet, int $row, string $label): void
    {
        $sheet->mergeCells("A{$row}:C{$row}");
        $sheet->setCellValue("A{$row}", $label);
        $sheet->getStyle("A{$row}:C{$row}")->getFont()->setBold(true)->setSize(10)->setColor((new Color())->setRGB(self::COLOR_PRIMARY));
        $sheet->getStyle("A{$row}:C{$row}")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::COLOR_ALT_ROW);
        $sheet->getStyle("A{$row}:C{$row}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
        $sheet->getRowDimension($row)->setRowHeight(18);
    }

    // ══════════════════════════════════════════════════════════════
    //  FORMATTING HELPERS
    // ══════════════════════════════════════════════════════════════

    private function writeChartSheetTitle(Worksheet $sheet, string $title): void
    {
        $sheet->mergeCells('A1:J1');
        $sheet->setCellValue('A1', $title);
        $this->applyTitleStyle($sheet, 'A1:J1', self::COLOR_PRIMARY, true);
        $sheet->getRowDimension(1)->setRowHeight(32);

        $sheet->mergeCells('A2:J2');
        $sheet->setCellValue('A2', 'Generated: '.now()->format('F j, Y \a\t g:i A').'  |  MSWDO Analysis System');
        $sheet->getStyle('A2:J2')->applyFromArray([
            'font'      => ['size' => 9, 'italic' => true, 'color' => ['rgb' => self::COLOR_SECONDARY]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => self::COLOR_PRIMARY]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getRowDimension(2)->setRowHeight(16);
        $sheet->getRowDimension(3)->setRowHeight(6);
    }

    private function applyChartSheetLayout(Worksheet $sheet): void
    {
        $sheet->getPageSetup()
            ->setOrientation(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_PORTRAIT)
            ->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4)
            ->setFitToWidth(1)->setFitToHeight(0);
        $sheet->getPageMargins()->setTop(0.5)->setBottom(0.5)->setLeft(0.5)->setRight(0.5);
        $sheet->setPrintGridlines(false);
        $sheet->setShowGridlines(true);
    }

    private function writeSheetTitle(Worksheet $sheet, string $title, string $subtitle, int $colCount): void
    {
        $lastCol = Coordinate::stringFromColumnIndex($colCount);
        $sheet->mergeCells("A1:{$lastCol}1");
        $sheet->setCellValue('A1', $title);
        $this->applyTitleStyle($sheet, "A1:{$lastCol}1", self::COLOR_PRIMARY, true);
        $sheet->getRowDimension(1)->setRowHeight(32);
        $sheet->mergeCells("A2:{$lastCol}2");
        $sheet->setCellValue('A2', $subtitle);
        $sheet->getStyle("A2:{$lastCol}2")->applyFromArray([
            'font'      => ['size' => 9, 'italic' => true, 'color' => ['rgb' => self::COLOR_SECONDARY]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => self::COLOR_PRIMARY]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getRowDimension(2)->setRowHeight(16);
        $sheet->getRowDimension(3)->setRowHeight(6);
    }

    private function applyTitleStyle(Worksheet $sheet, string $range, string $bgColor, bool $center = true): void
    {
        $sheet->getStyle($range)->applyFromArray([
            'font'      => ['bold' => true, 'size' => self::FONT_TITLE, 'color' => ['rgb' => self::COLOR_WHITE]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $bgColor]],
            'alignment' => ['horizontal' => $center ? Alignment::HORIZONTAL_CENTER : Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
    }

    private function writeHeaders(Worksheet $sheet, int $row, array $headers, string $bgColor): void
    {
        foreach ($headers as $colIdx => $header) {
            $col = Coordinate::stringFromColumnIndex($colIdx + 1);
            $sheet->setCellValue("{$col}{$row}", $header);
        }
        $lastCol = Coordinate::stringFromColumnIndex(count($headers));
        $sheet->getStyle("A{$row}:{$lastCol}{$row}")->applyFromArray([
            'font'      => ['bold' => true, 'size' => self::FONT_HEADER, 'color' => ['rgb' => self::COLOR_WHITE]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $bgColor]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'AAAAAA']]],
        ]);
        $sheet->getRowDimension($row)->setRowHeight(22);
        $sheet->freezePane("A".($row + 1));
        $sheet->setAutoFilter("A{$row}:{$lastCol}{$row}");
    }

    private function writeDataRow(Worksheet $sheet, int $row, array $data, bool $alternate): void
    {
        foreach ($data as $colIdx => $value) {
            $col = Coordinate::stringFromColumnIndex($colIdx + 1);
            $sheet->setCellValue("{$col}{$row}", $value);
        }
        $lastCol   = Coordinate::stringFromColumnIndex(count($data));
        $fillColor = $alternate ? self::COLOR_ALT_ROW : self::COLOR_WHITE;
        $sheet->getStyle("A{$row}:{$lastCol}{$row}")->applyFromArray([
            'font'      => ['size' => self::FONT_BODY],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $fillColor]],
            'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => self::COLOR_BORDER]]],
        ]);
        for ($i = 1; $i <= count($data); $i++) {
            $col   = Coordinate::stringFromColumnIndex($i);
            $align = is_numeric($data[$i - 1]) ? Alignment::HORIZONTAL_RIGHT : Alignment::HORIZONTAL_LEFT;
            $sheet->getStyle("{$col}{$row}")->getAlignment()->setHorizontal($align);
        }
        $sheet->getRowDimension($row)->setRowHeight(15);
    }

    private function writeEmptyState(Worksheet $sheet, int $row, int $colCount, string $msg): void
    {
        $lastCol = Coordinate::stringFromColumnIndex($colCount);
        $sheet->mergeCells("A{$row}:{$lastCol}{$row}");
        $sheet->setCellValue("A{$row}", $msg);
        $sheet->getStyle("A{$row}:{$lastCol}{$row}")->applyFromArray([
            'font'      => ['italic' => true, 'size' => 9, 'color' => ['rgb' => '64748B']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);
        $sheet->getRowDimension($row)->setRowHeight(20);
    }

    private function applySheetLayout(Worksheet $sheet, int $colCount, int $lastDataRow, int $headerRow, array $colWidths, string $orientation): void
    {
        foreach ($colWidths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }
        $lastCol = Coordinate::stringFromColumnIndex($colCount);
        $sheet->getPageSetup()->setPrintArea("A1:{$lastCol}{$lastDataRow}");
        $sheet->getPageSetup()->setRowsToRepeatAtTopByStartAndEnd($headerRow, $headerRow);
        $orientConst = $orientation === 'landscape'
            ? \PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_LANDSCAPE
            : \PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_PORTRAIT;
        $sheet->getPageSetup()->setOrientation($orientConst)
            ->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4)
            ->setFitToWidth(1)->setFitToHeight(0)->setHorizontalCentered(true);
        $sheet->getPageMargins()->setTop(0.75)->setBottom(0.75)->setLeft(0.75)->setRight(0.75)->setHeader(0.3)->setFooter(0.3);
        $sheet->getHeaderFooter()
            ->setOddHeader('&L&"Arial,Bold"&10MSWDO Analysis System&C'.$sheet->getTitle().'&R'.now()->format('Y-m-d'))
            ->setOddFooter('&LConfidential — MSWDO&CPage &P of &N&RGenerated: '.now()->format('Y-m-d H:i'));
        $sheet->setPrintGridlines(false);
        $sheet->setShowGridlines(true);
    }

    private function rowToCell(string $col, int $row): string
    {
        return $col . $row;
    }

    private function buildSubtitle(?string $m, ?int $y): string
    {
        $parts = [];
        if ($m) $parts[] = "Municipality: {$m}";
        if ($y) $parts[] = "Year: {$y}";
        if (empty($parts)) $parts[] = 'All Municipalities · All Years';
        $parts[] = 'Generated: '.now()->format('F j, Y \a\t g:i A');
        return implode('  |  ', $parts);
    }

    public function buildFilename(?string $m, ?int $y): string
    {
        $muniSlug = $m ? strtolower(preg_replace('/[^a-zA-Z0-9_-]/', '_', $m)) : 'all_municipalities';
        $yearSlug = $y ? (string)$y : 'all_years';
        return "{$muniSlug}_{$yearSlug}_data_export.xlsx";
    }
}
